---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    telegram-chat-id: AgB/sJ4eh3YfpuQlZ5zaT4EnQ74vOtYwmly5cs529N8wxkbuRi5LOmvbySkHvAu5Wbl2871cTvckrAXY+hYM6/wx84mtznl4Rn6KKX0ZbkxVO2/JewMbLjY3FtzDu7H13J9HmLbTEXycuwvHKqNyyub3pAsSzmVbzBIJhIG7UOewdsLkMhJIEB3kyDJmFsVuHgypXz2fF8/4AdXPsGnCa1vWF0KVaJu5kH/R9Y83/s9BV192I6lTiyHEzzs0tIaRrcfU05c5KHcv1V/PuO1zppR2n6FWTEA1lLJqjLGkr9uDGf+l94Nhuc+9KVUY2eL/t8/Gx2oBUexEL1onvgVOA/Xhy/TRCU4pGWREseGX9d1Gc0OXF/PI4u1q66HF1dFHx18k8x4IENC+mNFCi6+A2Fc+05+nefWpaARLdf/odktD43fIO17UP7Lz3XANJdXiTjumk8WfWOYpnr0/blwAF6m630AGTPoCinMD9zWtHWAzuUiV0RskvnpwNkCUFyGs3K8gU0yJI+ECZQUV5QsBWIzO2y4ducmC+IENqGhKRPFbouIjFBBKjhr9E8Ah3snEwTOoLYFEZcqWMWsQ16nnn8t/UTqdUl/Q6qENWjPTjftWM7KtXiCCK6IlSmm2kO4XHgv5guQ2yJ3I8fBanyvZx24SjMvTcIPJtBg7oww3UtHfGxf3toQYgg7S1qLqxgZnY4axOsLaWwajrS0=
    telegram-token: AgCPfMglYSv1Vf4aF68/auos4YX7uEttvPe64PJ7YO0/LBI+roHP4dOUprW2XpKjKh3sUyEiNw3LIXVGRwSidOSxmqCTSxUeRNgHyhWMImY56eN25RbAOr1abc2BBWmaWVFZpQsI0iT+YWDZp1aqssBW/tgNVn+cYCJ4gCdzbDmzPaqV7FJ07pt41ul9HeFUuYdgYidKn03wj1BOb1DSSuLMRG98fR0wfOFsQalwxCNnI947/GkhAJtk9XkN6bTO+NmUdPOPzS3+XsZs4GXKvsglZfbjIxMlN189Q3fs2Xs2P5VkP/dQJkv4fnLxXIzgeFH0gjtQSv/LdM0ht7fPFwAnVM4zAv2bHjc+ertD1oUuuPGGvJgmJ/IMauFYmXF8rePeM52eTHY1vtNwfm+kteazyH7gMkgCQGiez02DxSeBeWXxbVOT8k7Py2iOEJKslCsw/FazCci5VXkUg7LNUvTos55OPhoNtrHbg5A3yDCRi51dw1d8g28CDmxCrv2eQW8i5iWEBVDsAph/JaMXhts9lqVVBFEiwvpFTosd/uCM/eZS+UnGpMmnB49VkoL+EW8LSBLHXDR2AfoiGD5FYqjsOYj+nxwUjOox4lbY/sTC1XBsW8PZIzczRvlw/8t7qxoNRFEhvzl9qC5XWEirNAKQFExQJOSZ2XHIh34Rx+PMC9/rkUgT0EZnShkeRoAOBOm7Lv3KvOERvPPATG2ymyUNFqoDEq35jbNO728dTHdClVjULVJSm8nFg3zCEY+3
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
