---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    telegram-chat-id: AgBSwYINHaEq7whGnFfzeKgNAMN6Oy5AG2nn69G2pBG4IyO1C3J270Zjy8fqT7USS7TpK7/wTc0B418UYeSynK3td4gfTEJQU6mK9/9i5y6XE+iQv8pvRpwWZEIPEMp/JOvt9hgqebkHzdNwVoqBfrJgtoklYCyBw6yZzXTc/inb395EKVPo3quI4tGjMFiX+LYnGq8Oeb8d3SVQ4KdQdnFLF3uuEvp7eXfuguXn7ZFILqeHVk937Qq3YButDb48DxMzANt9foxQ0UCWRTmXKbyDKncTtav36YyUGY5U8JSGaWZmhlxd/OdeidItg2oqMpnRnucw4LUfJA28pwQIUaUbwB24DLJAe13lC2KJEhKdTZzsnKFWCiMSyPwEwgf5B5NfDEivdv+PgPxkjoq/2LkguLpXwHXKINz/bMjXRK8RvHkqkWH0o1j86L0rUPaG3Lv5hrzbw3PHCByhHxpwLkUpeyxOSzaS4sUSzaTxYQ6hnEfjBFmgFImvWB2ygFQnNcTP5+FFgyXvqGWED7/+esMtaigmmm4CTQh9X2hBpBxUpRwUyximdg7JGMJsPKZr1F6822QYqxbrFdrW0/2Ua3GY2ERu7LFyK+OmDBI0mE/RdzZNFv3i4ikDUsZFfC4OyrZRgeNzE15AOjZBDuqIjlIL/YrMqifohVsaVsyHEXfoR+U7njWOCevrzZi0TD21rRdD89okvj1QSDU=
    telegram-token: AgAgDhrmPYp9Ti/CYCBUoy5yXZ19uW8pW9gvznlX4yntnFH++llumStNkaOhEADvxZAldHTHHj/+i3cQpUZYQnNrSB2hpEuGIm071kJVOSzaRLuTn7Oav4/P53r6ZwUtPsLPCJ5aD3f/2vU/RDcL/HRHyfMbtL7lVbsqHwNeSWAyrc9aUHRVV2l9FvKbaOs+ASPz0M9PvqFHXjunuwOdPrR6aFwvU/ekFw9GnsfDarGDBFo1Ie3JT9QUPhmOgxkl2JFZcoCWrTSm2/1xibHiA9CzY8M0XXEikLXs2tUoL5amxzmmZzKUhmIE5Nz5EGMApSeDHZ//S8G67h0RrAte5A9WRCAGwPINgYo+9lqRiMHwX7lN9ITqQ/psXeW5OxFsaYYqdWzn/gltu6lBSVupHheHdzx59SKp3zZko6Zau/9Hn9lZ9TuCrXdx/r0TGf95sUKm0AD4UNYFT5RmcCwGbLVZNYp5joY6aQyedsxUz1Bd+SIuUCfGhepvFCdY7VTQ46Ld5OJQDH16ncSQcOeZuHBdJk5H1PuqI2Y0l2RkpiYDfPyx2SYRT/UdhjT7MPtIcp5SQZ2NGAh7QeZ9iu5kw50Z/je6p2b1TJrNvFAbHZQDfWduomIUBL2rneMiecnR7AdUMZS9OdniVw038VfjVPjx/zvIrfb3tCKepY+a552idKnicMQcAef86msNHnKHSZvrjWHzYVIjdS5cjfw3F2TdFZIDaFl+ESQhQlvTJJwuc1pbJz571ZF0hnMgwYp/
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
